server:
  port: 8082 
spring:
  application:
    name: resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          # O Spring vai bater nessa URL ao iniciar para baixar as chaves públicas (JWK Set)
          # Ele valida se o token foi assinado por ESSE emissor.
          issuer-uri: http://localhost:8080/realms/bff